#!/usr/bin/env python
"""
    Command line interface to the cuckoo tool.
    Designed to be run independently of django
"""
import sys, os
sys.path.append('.')

if os.path.exists('settings.py'):
    os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
else:
    print "Please create a settings file. See django conf for more details."
    sys.exit(1)

from django.conf import settings
settings.INSTALLED_APPS = ("cuckoo",)
settings.TIME_ZONE = 'Pacific/Auckland'

from django.core import management

from cuckoo.management.commands.cuckoo import command_list

if __name__ == "__main__":
    argv = sys.argv
    if 'init' in argv:
        sys.argv = [argv[0]] + ['syncdb']
    elif 'help' in argv or not any([cmd in argv for cmd in command_list] ): 
        argv.insert(1, 'help')
        argv.insert(2, 'cuckoo')
        argv[0] = ''
    else:
        argv.insert(1, 'cuckoo')
    management.execute_from_command_line()

